### PR TITLE
Fix forced features typo

### PR DESCRIPTION
**Pull request by aburke07**
Fixes a typo made in https://github.com/iFixit/growthbook-php/pull/2/commits/72700bbec1155c979f3deab9ff072c0e38489a62

### CODE REVIEW

**Comment by aburke07** [comment]
We can wait on https://github.com/growthbook/growthbook-php/pull/26 and merge that in too.

**Comment by jordycosta** [comment]
QA 🟢

**Review by hcutrone — APPROVED** [review]
CR 🌯

**Comment by hcutrone** [comment]
deploy_block 🌯 in case you wanted to wait for https://github.com/growthbook/growthbook-php/pull/26

**Comment by aburke07** [comment]
Lets wait for https://github.com/growthbook/growthbook-php/pull/26. This would require changes in our PHP app too, and I don't think its worth an entire fork for this change.

**Pull request closed without merging**
